### ISSUE TITLE
Why isn't docker labeling the volumes correctly when using SELinux

### ISSUE THREAD

**Issue by runcom** [projectatomic/docker-lvm-plugin#3] opened 2016-03-25 13:00 UTC
By default the volume should be labeled

svirt_sandbox_file_t:s0

If the user specifies

docker run -v foobar:/mnt:Z

Then docker should relabel the content specific to the container.
## 

copied from https://github.com/shishir-a412ed/docker-lvm-plugin/issues/7

**Comment by rhatdan** [comment] 2016-03-25 13:04
The problem here is we have no good way of dealing with this.  I brought this up with docker, but they never responded.  The problem is the devices is created at the mount time not at the create time.  In the case of local volumes they are labeling at create time.  Since the mount can happen multiple times, we really only want to do this once.  We could add an SELinux hack to check if the content is currently labeled, if not, then label.

https://github.com/docker/docker/issues/20859

**Comment by jmccormick2001** [comment] 2016-12-05 22:29
any update on this one?  I'm having to do workarounds to get volumes to work when in enforcing mode on fedora/centos.

**Comment by rhatdan** [comment] 2016-12-06 12:40
There is a fix in docker-1.13 for this issue.  The fix should go into the next release of docker-1.12 in Fedora 25/24.

**Comment by shishir-a412ed** [comment] 2018-06-27 14:24
@rhatdan I think this issue is fixed by https://github.com/moby/moby/pull/23024.
Can we close this ?

**Closed** 2018-06-27 15:44 UTC
Labels: bug
